First stab at reverse hierarchical display (bug 106)
kewisch/quickmove-extension pull request #128
Opened 2023-10-16 19:22 UTC by mclaborn

#106 

Here is my first stab at this. Notes:

1. I tried to use <span> with css for the bold account name, but it acted like it could not find the CSS definition in popus.css. I couldn't figure out how to use Inspector in the debug window to work on this. 
2. I reworked BaseItemList.repopulate() to call a sortItems() method which is overridden in TBFolderList and sorts if the corresponding preference is checked. 
3. I'm sorting the folder names on the display string, case insensitive. It might be better to sort a folder node at a time, probably won't matter in the long run. 
4. DE and FR translations are straight from Google Translate.

2023-10-25 11:11 UTC, kewisch requested changes
Just skimmed the review so far, might have a few more comments with more time, and will provide updated German translations. 

On debugging, there is an option to disable popup auto-hide, then you should be able to switch windows in the inspector, then you should be able to get to the contents.

For CSS in the webcomponents you need to adjust the CSS within that .js file, for anything outside of the webcomponent it will be popup.css. This will also help you separate the visual from the data.

2023-10-25 11:11 UTC, kewisch commented on src/common/foldernode.js
> +  get fullPathReversed() {
I think we should separate the display and data aspects. We can get the reversed parts with `getFullNameParts(true).reverse()`, then in the folder nodes we can use templating and css to set the styles.

On the gmail and empty components thing, I think we could generally filter out empty components in getFullNameparts, and maybe add an option skipGmail that would then always skip [Gmail] folders.

2023-10-25 11:11 UTC, kewisch commented on src/common/foldernode.js
>        node = node.parent;
```suggestion
    while (node && (!(node instanceof AccountNode) || includeAccountNode)) {
        parts.unshift(node.item.name);
        node = node.parent;
    }
```

(untested)

2023-10-25 15:22 UTC, mclaborn commented
I must be blind because I can't get the Inspector to show the pop up window. The Inspector for the add-on only shows the background page. 
When I try to open Developer Tools in the main Thunderbird  window it doesn't open. 
Any thoughts?

2023-11-09 15:55 UTC, mclaborn commented
Any ideas on this?

2024-01-20 21:01 UTC, kewisch commented
Hey, sorry for the radio silence. Around that time I was prepping for a large event at work and then I missed picking this up again after. If you try the developer tools in the add-on options, there is an option to disable popup auto-hide. Can you try that one and see if it shows up?

Otherwise, the main inspector in the toolbar, I'm not sure why it wouldn't show up. What it does is open another instance of Thunderbird and then connects the debugger. Can you try closing all other instances of Thunderbird maybe? Otherwise the folks in #maildev:mozilla.org on Matrix might be able to help you.

2024-01-24 17:03 UTC, mclaborn commented
I'm feeling stupid - can't get the inspector to show. Can you take a look and tell me what I'm doing wrong? https://www.loom.com/share/2a02d83666834a828f1acc1be8bcad92?sid=091156fa-1d5f-428f-b35b-08eeae660c05

2024-07-15 18:37 UTC, kewisch commented
You could try the full debugger that you can find in Tools > Developer Tools > Developer Toolbox. It will debug a lot more than the extension itself, but it is also more powerful.

2025-03-10 09:19 UTC, kewisch commented
I'm going to go ahead and close this for now, if you ever want to pick this up again let me know. For next time it might be easier we chat via Matrix, I'm a lot more responsive this way :) GitHub notifications don't really work well for me, which often makes me miss things.

2025-03-10 09:19 UTC, closed without merging